<?php
$poLang = array();
__('Order confirmed');
__('Customer information');
__('Text');
__('Heading');
__('Image with text');
__('Video');
__('Birthday subscription');
__('Reorder');
__('Social media');
__('Social sharing');
__('Call to action');
__('Custom html');
__('Navigation bar');
__('Collection list');
__('Social like');
__('Survey');
__('Header');
__('Discount');
__('Product comment');
__('Popup with timer');
__('Left Area');
__('Right Area');
$poLang['textarea'] = __('Free text');
$poLang['select'] = __('Select');
$poLang['radio'] = __('Radio');
$poLang['checkbox'] = __('Check-box');
?>
<script type="text/javascript">
var _E_sfCommonDeleteConfmessage = '<?php printf(__('Are you sure you want to delete the %s ? This action cannot be reversed.'),'{0}'); ?>';
var _E_sfCommonDeleteConfTitle = '<?php printf(__('Delete %s ?'),'{0}'); ?>';
var _E_sfCommonDeleteConfOkBtn = '<?php printf(__('Delete %s'),'{0}'); ?>';
var _E_sfCommonDeleteConfCancelBtn = '<?php _e('Cancel'); ?>';
var _E_question = '<?php _e('Question'); ?>';
var _E_Question = '<?php _e('Question'); ?>';
var _E_template = '<?php _e('Template'); ?>';
var _E_browserNotSupportFileReader = '<?php _e('This browser does not support FileReader.'); ?>';
var _E_imageFormatErr = "<?php _e("Image file is invalid. Make sure the format is valid (jpg/jpeg/png/gif/bmp) and the image isn't corrupted."); ?>";
var _E_tryAgain = '<?php _e('Sorry, please try again.'); ?>';
var _E_plzEnterName = '<?php _e('Please enter name.'); ?>';
var _E_plzEnterUrl = '<?php _e('Please enter URL.'); ?>';
var _E_plzEnterLogo = '<?php _e('Please enter logo.'); ?>';
var _E_app = '<?php _e('ReConvert'); ?>';
var _E_other = '<?php _e('shop'); ?>';
var _E_today = '<?php _e('Today'); ?>';
var _E_yesterday = '<?php _e('Yesterday'); ?>';
var _E_last7Days = '<?php _e('Last 7 days'); ?>';
var _E_last30Days = '<?php _e('Last 30 days'); ?>';
var _E_thisMonth = '<?php _e('This month'); ?>';
var _E_lastMonth = '<?php _e('Last month'); ?>';
var _E_custom = '<?php _e('Custom'); ?>';
var _E_apply = '<?php _e('Apply'); ?>';
var _E_cancel = '<?php _e('Cancel'); ?>';
var _E_from = '<?php _e('From'); ?>';
var _E_to = '<?php _e('To'); ?>';
var _E_cal_su = '<?php _e('Su'); ?>';
var _E_cal_mo = '<?php _e('Mo'); ?>';
var _E_cal_tu = '<?php _e('Tu'); ?>';
var _E_cal_we = '<?php _e('We'); ?>';
var _E_cal_th = '<?php _e('Th'); ?>';
var _E_cal_fr = '<?php _e('Fr'); ?>';
var _E_cal_sa = '<?php _e('Sa'); ?>';
var _E_january = '<?php _e('January'); ?>';
var _E_february = '<?php _e('February'); ?>';
var _E_march = '<?php _e('March'); ?>';
var _E_april = '<?php _e('April'); ?>';
var _E_may = '<?php _e('May'); ?>';
var _E_june = '<?php _e('June'); ?>';
var _E_july = '<?php _e('July'); ?>';
var _E_august = '<?php _e('August'); ?>';
var _E_september = '<?php _e('September'); ?>';
var _E_october = '<?php _e('October'); ?>';
var _E_november = '<?php _e('November'); ?>';
var _E_december = '<?php _e('December'); ?>';
var _E_bt_disable = '<?php _e('Disable ReConvert'); ?>';
var _E_bt_enable = '<?php _e('Enable ReConvert'); ?>';
var _E_tobi_error = '<?php _e('Tobi application not installed. Please install it and check again.'); ?>';
var _E_tobi_install = '<?php _e('Tobi application installed.'); ?>';
var _E_tp_rm_succes = '<?php _e('Selected integration removed successfully.'); ?>';
var _E_tp_rm_error = '<?php _e('Something wrong. Try again later.'); ?>';
var _E_tp_tobi_synched = '<?php _e('Synced with Tobi'); ?>';
var _E_tp_select = '<?php _e('Select'); ?>';
</script>