<?php
define("MSG_ACCOUNT_NOT_SARTED", "Your account is not turn on yet. Please click on the verify link in the mail.");
define("MSG_CAPTCHA_WRONG", "Captcha was wrong!");
define("MSG_COOKIE_INVALID", "Invalid cookie");
define("MSG_DATABASE_ERR", "Error for Database connection.");
define("MSG_EMAIL_ALREADY_EXISTS", "This email address is already used. Please use the \"I forgot my password\" page if you don't remember it.");
define("MSG_EMAIL_CHANGE_FAILED", "Sorry, your email changing failed.");
define("MSG_EMAIL_CHANGED_SUCCESSFULLY", "Your email changed successfully. New email ");
define("MSG_EMAIL_VOID", "Email cannot be empty");
define("MSG_EMAIL_WRONG", "Your email address is not in a valid email format");
define("MSG_EMAIL_SAMEAS_OLD_ONE", "Sorry, that email address is the same as your current one. Please choose another one.");
define("MSG_EMAIL_TOO_LARGE", "Email can't be longer than 64 characters");
define("MSG_VOID_LINK_PARAMETER_VOID", "Empty link parameter data.");
define("MSG_LOGGED_OUT", "You've been logged out.");
define("MSG_LOGIN_FAILED", "Login failed.");
define("MSG_OLD_PASSWORD_WRONG", "Old password was wrong.");
define("MSG_PASSWORD_CONFIRM", "Password and confirm-password  are not  same");
define("MSG_PASSWORD_CHANGE_FAILED", "Sorry, your password changing failed.");
define("MSG_PASSWORD_CHANGED_SUCCESSFULLY", "Password successfully changed!!");
define("MSG_VERIFICATION_EMAIL_SUCCESSFULLY", "Email verificatioin successfully!!");
define("MSG_PASSWORD_VOID", "Password  was empty");
define("MSG_PASSWORD_RESET_EMAIL_FAILED", "Error : Password reset Email NOT successfully sent!! ");
define("MSG_PASSWORD_RESET_EMAIL_SUCCESSFULLY_SENT", "Password reset Email successfully sent!");
define("MSG_PASSWORD_TOO_SMALL", "Passwords must contain at least 6 characters");
define("MSG_PASSWORD_WRONG", "Wrong password.Please Try again.");
define("MSG_PASSWORD_WRONG_3TIMES","You have blocked. Please wait 30 seconds to try again.");
define("MSG_REGISTRATION_TURNON_NOT_SUCCESSFUL", "Sorry, no such id/verification code combination here...");
define("MSG_REGISTRATION_TURNON_SUCCESSFUL", "Activation was successfully ended! You can now log in!");
define("MSG_REGISTRATION_FAILED", "Sorry, your registration failed. Please try again.");
define("MSG_RESET_LINK_EXPIRED", "Your reset link has expired. Please use the reset link within  hour.");
define("MSG_VERIFICATION_EMAIL_ERR", "Sorry, we could not send you an verification email. Your account has not been created.");
define("MSG_VERIFICATION_EMAIL_NOT_SENT", "Error : Verification Email not sent!  ");
define("MSG_VERIFICATION_EMAIL_SENT", "Your account has been created successfully. Please click the VERIFICATION LINK within email.");
define("MSG_USER_DOES_NOT_EXIST", "This user does not exist");
define("MSG_USER_DOES_NOT_EXIST_OR_VERIFIED", "This user does not exist or already verified");
define("MSG_USERNAME_LENGTH", "Username can't be shorter than 2 or longer than 64 characters");
define("MSG_USERNAME_CHANGE_FAILED", "Sorry, your chosen username renaming failed");
define("MSG_USERNAME_CHANGED_SUCCESSFULLY", "Your username has been changed successfully.");
define("MSG_RESET_NEW_PASSWORD", "Reset your password.");
define("MSG_USERNAME_EMPTY", "Username  was empty");
define("MSG_USERNAME_ALREADYEXISTS", "Sorry, that username is already exist. Please choose another one.");
define("MSG_USERNAME_INVALID", "Username does not fit the name scheme: only a-z and numbers are allowed, 2 to 64 characters");
define("MSG_USERNAME_SAMEAS_OLD_ONE", "Sorry, that username is the same as your current one. Please choose another one.");
define("MSG_NEW_STORE_ADD", "New store added to account");
define("MSG_WORD_BACK_TO_LOGIN", "Back to Login Page");
define("MSG_WORD_CHANGE_EMAIL", "Change email");
define("MSG_WORD_CHANGE_PASSWORD", "Change password");
define("MSG_WORD_CHANGE_USERNAME", "Change username");
define("MSG_WORD_CURRENTLY", "currently");
define("MSG_WORD_EDIT_USER_DATA", "Edit user information");
define("MSG_WORD_EDIT_YOUR_CREDENTIALS", "You are logged in and you can edit your credentials here");
define("MSG_WORD_FORGOT_PASSWORD", "forgot  password");
define("MSG_WORD_LOGIN", "Log in");
define("MSG_WORD_LOGOUT", "Log out");
define("MSG_WORD_NEW_EMAIL", "New email");
define("MSG_WORD_NEW_PASSWORD", "New password");
define("MSG_WORD_NEW_PASSWORD_CONFIRM", "confirm password");
define("MSG_WORD_NEW_USERNAME", "New username (username can't be empty and must be a-z,A-Z,0-9 and 2-64 characters)");
define("MSG_WORD_OLD_PASSWORD", "Your OLD Password");
define("MSG_WORD_PASSWORD", "Password");
define("MSG_WORD_PROFILE_IMAGE", "Your profile image:");
define("MSG_WORD_REGISTRATION", "Registration");
define("MSG_WORD_REGISTRATION_NEW_ACCOUNT", "Registration new account");
define("MSG_WORD_REGISTRATION_CAPTCHA", "Please enter these characters");
define("MSG_WORD_REGISTRATION_EMAIL", "User's email (please Enter email , you'll get a verification mail with an verify link)");
define("MSG_WORD_REGISTRATION_PASSWORD", "Password minimum 6 characters!");
define("MSG_WORD_REGISTRATION_PASSWORD_REPEAT", "Password repeat");
define("MSG_WORD_REGISTRATION_USERNAME", "Username (only letters and numbers, 2 to 64 characters)");
define("MSG_WORD_REMEMBER_ME", "Keep me logged in (for 2 weeks)");
define("MSG_WORD_REQUEST_PASSWORD_RESET", "Request a password reset. Enter your username and you'll get a mail with instructions:");
define("MSG_WORD_RESET_PASSWORD", "Reset my password");
define("MSG_WORD_SUBMIT_NEW_PASSWORD", "Submit new password");
define("MSG_WORD_USERNAME", "Username");
define("MSG_WORD_YOU_ARE_LOGGED_IN_AS", "You are logged in as ");

define("MSG_RECORD_ADD", "New record addded succesfully");
define("MSG_RECORD_DELETE", "Record deleted succesfully");
define("MSG_PROFILE_UPDATE", "Profile updated succesfully");
define("MSG_PROFILE_UPDATE_ERR", "error : Profile can't updated ");
define("MSG_RECORD_UPDATE", "Record updated succesfully");
define("MSG_EMAIL_SEND_SUCCESS", "Email send succesfully");
define("MSG_EMAIL_NOT_SEND", "Error : Email not send");
define("MSG_EMAIL_ALREADYEXITS", "Email already exist");